### ISSUE TITLE
Login incorrect after entering seemingly correct login details

### ISSUE THREAD

**Issue by sampittko** [fabimc/strapi-provider-upload-ftp#1]
Error log that I get from Strapi:
`
2020-09-03T14:09:59.169451+00:00 app[web.1]: [2020-09-03T14:09:59.169Z] debug GET /upload/files/count (30 ms) 200
2020-09-03T14:10:06.341116+00:00 app[web.1]: [2020-09-03T14:10:06.340Z] error Error: Login incorrect.
2020-09-03T14:10:06.341127+00:00 app[web.1]: at makeError (/app/node_modules/ftp/lib/connection.js:1067:13)
2020-09-03T14:10:06.341127+00:00 app[web.1]: at Parser.<anonymous> (/app/node_modules/ftp/lib/connection.js:113:25)
2020-09-03T14:10:06.341128+00:00 app[web.1]: at Parser.emit (events.js:314:20)
2020-09-03T14:10:06.341128+00:00 app[web.1]: at Parser._write (/app/node_modules/ftp/lib/parser.js:59:10)
2020-09-03T14:10:06.341129+00:00 app[web.1]: at writeOrBuffer (_stream_writable.js:352:12)
2020-09-03T14:10:06.341129+00:00 app[web.1]: at Parser.Writable.write (_stream_writable.js:303:10)
2020-09-03T14:10:06.341130+00:00 app[web.1]: at Socket.ondata (/app/node_modules/ftp/lib/connection.js:273:20)
2020-09-03T14:10:06.341130+00:00 app[web.1]: at Socket.emit (events.js:314:20)
2020-09-03T14:10:06.341130+00:00 app[web.1]: at addChunk (_stream_readable.js:303:12)
2020-09-03T14:10:06.341131+00:00 app[web.1]: at readableAddChunk (_stream_readable.js:279:9)
2020-09-03T14:10:06.341131+00:00 app[web.1]: at Socket.Readable.push (_stream_readable.js:218:10)
2020-09-03T14:10:06.341132+00:00 app[web.1]: at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
`

Login details (inside env):
**FTP_BASEPATH**: /path/to/upload/dir/
**FTP_BASEURL**: ftp://{IP_ADDR}/path/to/upload/dir/
**FTP_HOST**: {IP_ADDR}
**FTP_PASSWORD**: mypassword (containing special characters, tried also password without them)
**FTP_PORT**: 21
**FTP_USER**: myusername

Is there any problem that you can see? I tried changing login details in various ways but it did not help either.

Thanks!

**Comment by fabimc** [comment]
I don't see any obvious problems. Did you check the credentials in a ftp client first? 
We use the plugin everyday in my org and works without login issues.

**Comment by sampittko** [comment]
haven't had a look into it since I created this issue and didn't have time to debug it, I also switched to different CMS so it is not relevant to me anymore, hope you can resolve it if it is occurring still ✌🏼

**Comment by fabimc** [comment]
Could not reproduce
